apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: news-se
spec:
  hosts:
    - news-traffic-mesh-news.apps.ocp4.example.com
  ports:
    - name: http-80
      number: 80
      protocol: http
