[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore all example certs
    '''\/example.*\.pem$''',
                
    # Ignore anything with these words anywhere in the path
    '''htpasswd''',
    '''wildcard''',
    '''mariadb-root-password''',
    '''mariadb-password''',
    '''wildcard-api-key''',
    '''key''',
    '''json''',

    # Ignore some long path
    '''examples\/some\/long\/path\/server.key$''',
  ]
        
  # Ignore based on any subset of the line
  regexes = [
    # Ignore lines containing pickles
    '''pickles''',
  ]
