apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - ldap:
      attributes:
        id:
          - dn
        email:
          - mail
        name:
          - cn
        preferredUsername:
          - uid
      bindDN: CHANGE_ME
      bindPassword:
        name: CHANGE_ME
      ca:
        name: CHANGE_ME
      insecure: false
      url: >-
        ldaps://rhds.ocp4.example.com/dc=example,dc=com?uid
    mappingMethod: claim
    name: CHANGE_ME
    type: LDAP