apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: SUBSCRIPTION
  namespace: OPERATOR_NAMESPACE
spec:
  channel: CHANNEL
  installPlanApproval: Automatic
  name: OPERATOR
  source: CATALOG
  sourceNamespace: CATALOG_NAMESPACE

