apiVersion: v1
clusters:
- cluster:
    server: https://api.ocp4.example.com:6443
  name: api-ocp4-example-com:6443
contexts:
- context:
    cluster: api-ocp4-example-com:6443
    namespace: default
    user: admin/api-ocp4-example-com:6443
  name: default/api-ocp4-example-com:6443/admin
- context:
    cluster: api-ocp4-example-com:6443
    namespace: metallb-system
    user: admin/api-ocp4-example-com:6443
  name: metallb-system/api-ocp4-example-com:6443/admin
current-context: metallb-system/api-ocp4-example-com:6443/admin
kind: Config
preferences: {}
users:
- name: admin/api-ocp4-example-com:6443
  user:
    token: sha256~d21upsexxxLLyW62UZm_01lhFiCEKEDvKG6KiT1oHuw
