apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: payment-dr
  namespace: release-mesh
spec:
  host: payment
  subsets:
  - labels:
      version: v1
    name: v1
  - labels:
      version: v2
    name: v2
