---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-pruner-sa
  namespace: appsec-prune
  labels:
    ge: appsec-prune
    app: crictl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: image-pruner
  namespace: appsec-prune
  labels:
    ge: appsec-prune
    app: crictl
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-pruner
  namespace: appsec-prune
  labels:
    ge: appsec-prune
    app: crictl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: image-pruner
subjects:
- kind: ServiceAccount
  name: image-pruner-sa
  namespace: appsec-prune
