apiVersion: v1
kind: ConfigMap
metadata:
  name: config-app
  namespace: appsec-api
data:
  config.yaml: |
    application:
      name: "config-app"
      description: "API that exposes its configuration"
