---
apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: gls-metallb-ipaddresspool
  namespace: metallb-system
  labels:
    zone: gls
spec:
  addresses:
  - 192.168.50.20-192.168.50.20
  autoAssign: true
  avoidBuggyIPs: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: gls-metallb-l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - gls-metallb-ipaddresspool