apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: network-review
spec:
  selector:
    app: product
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 443
      targetPort: 8080
      name: tls
